#目前测试配置文件只能用application命名
server:
  port: 9999
  
spring:
  application:
    name: springbootadminserver
  boot:
    admin:
      ui:
        title: 'Spring Boot Admin for me'
    
    



             
    
   
     
     